# -*- coding: utf-8 -*-
"""21301259_Aovejeet Saha_A1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edjdX6F8mE_DqjSc17TxFhGdVdWAy79M
"""

# Lab01_solver.py

import heapq
from collections import deque
import sys

# ==========PART1: A*Maze Solver==========

def read_maze_input(file_path):
    with open(file_path, 'r') as f:
        n, m = map(int, f.readline().split())
        a, b = map(int, f.readline().split())
        c, d = map(int, f.readline().split())
        maze = [list(f.readline().strip()) for _ in range(n)]
    return n, m, (a, b), (c, d), maze

def astar(n, m, start, goal, maze):
    directions = [(0, 1, 'R'), (1, 0, 'D'), (0, -1, 'L'), (-1, 0, 'U')]
    visited = set()
    heap = [(manhattan(start, goal), 0, start[0], start[1], '')]

def manhattan(u1, u2):
    return abs(u1[0]-u2[0]) + abs(u1[1]-u2[1])

    while heap:
        est_total, costing, x, y, path = heapq.heappop(heap)
        if (x, y) == goal:
            return costing, path
        if (x, y) in visited:
            continue
        visited.add((x, y))
        for dx, dy, move in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < m and maze[nx][ny] == '0' and (nx, ny) not in visited:
                new_costing = costing + 1
                est = new_costing + manhattan((nx, ny), goal)
                heapq.heappush(heap, (est, new_costing, nx, ny, path + move))
    return -1, ''

def write_maze_output(file_path, costing, path):
    with open(file_path, 'w') as f:
        f.write(f"{cost}\n")
        if costing != -1:
            f.write(f"{path}\n")

# ========== PART2: Heuristic Admissibility Checker==========

def read_heuristic_input(file_path):
    with open(file_path, 'r') as f:
        n, m = map(int, f.readline().split())
        a, b = map(int, f.readline().split())
        heuristics = {}

        edges = {i: [] for i in range(1, n+1)}

        for _ in range(m):
            u, v = map(int, f.readline().split())
            edges[v].append(u)
            edges[u].append(v)

        for _ in range(n):
            x, y = map(int, f.readline().split())
            heuristics[x] = y

    return n, m, a, b, heuristics, edges

def bfs_shortest_paths(goal, n, edges):
    dist = {i: float('inf') for j in range(1, n+1)}
    dist[goal] = 0
    queue = deque([goal])
    while queue:
        u = queue.popleft()
        for v in edges[u]:
            if dist[v] == float('inf'):
                dist[v] = dist[u] + 1
                queue.append(v)
    return dist

def check_admissibility(n, goal, heuristics, edges):
    dist = bfs_shortest_paths(goal, n, edges)
    inadmissible = []
    for node in heuristics:
        if heuristics[node] > dist[node]:
            inadmissible.append(node)
    return inadmissible

def write_heuristic_output(file_path, inadmissible):
    with open(file_path, 'w') as f:
        if not inadmissible:
            f.write("1\n")
        else:
            f.write("0\n")
            f.write(" ".join(map(str, sorted(inadmissible))) + "\n")